/** Explicit public route registry. Unknown paths remain real 404s. */
export const GUIDES = [
  { path: "/best-used-cars-in-bloomington-ca", title: "Choosing a used sedan", body: "sedan", intro: "Start with the driving you do every day. Compare passenger space, mileage, equipment and the complete listed sale price—not just a model name.", sections: ["Compare BMW, Chevrolet and Toyota sedans by the specific vehicle's equipment and condition.", "Check maintenance records and request an independent inspection before deciding.", "Use the inventory filters to narrow the options, then request a test drive to compare comfort and visibility."] },
  { path: "/best-used-coupes-in-bloomington-ca", title: "Finding your next coupe", body: "coupe", intro: "The captured Carfam guide highlights Dodge and Ford coupes. Choose the specific car that fits your driving needs rather than assuming every trim has the same performance.", sections: ["Compare seating, cargo access and everyday practicality alongside styling.", "Review the actual engine, transmission and equipment shown on each vehicle page.", "Request a test drive and ask about condition and maintenance history."] },
  { path: "/best-used-suvs-in-rialto-ca", title: "Choosing a used SUV", body: "suv", intro: "Compare family space, seating, cargo room and drivetrain across the actual SUV listings.", sections: ["The original guide discusses Acura, Chevrolet and Honda. Specifications vary by year and trim; use each vehicle's recorded details.", "Check rear-seat access and cargo space with the people and equipment you normally carry.", "Some technical claims in the older source guide need review. This demo does not repeat those unverified engine or fuel-economy claims."] },
  { path: "/best-used-trucks-in-rialto-ca", title: "Finding the right used truck", body: "pickup", intro: "The source guide discusses Nissan Frontier, GMC Sierra and Toyota Tundra models. Compare the individual listings for your work and daily-driving needs.", sections: ["Consider cab layout, bed size, drivetrain and mileage.", "Do not infer towing or payload capacity from the model name. Confirm the specific vehicle's ratings and equipment.", "Inspect condition and ask about maintenance before requesting a test drive."] },
  { path: "/buying-a-car-in-bloomington-ca", title: "A more confident used-car purchase", body: null, intro: "The original buying guide focuses on sales pressure, changing quotes and being steered toward a vehicle you did not want.", sections: ["Keep your needs and budget clear. Ask for the price and fee breakdown in writing.", "If an advertised vehicle is unavailable, choose whether to consider alternatives; you do not need to abandon your original budget.", "Take time to review documents and vehicle condition. Ask questions whenever a term or claim is unclear."] },
  { path: "/used-car-rialto-used-car-dealership-guide", title: "Your guide to shopping used cars in Rialto", body: null, intro: "Carfam's captured inventory includes sedans, SUVs, trucks, EVs and hybrids. Start with your lifestyle, passenger needs and budget.", sections: ["A sedan may suit commuting; an SUV adds passenger and cargo flexibility; a truck serves different hauling needs.", "Compare year, mileage, condition, equipment and vehicle history rather than relying only on a brand's reputation.", "Explore financing separately and confirm terms with the provider. This demo does not offer credit decisions."] },
  { path: "/used-ev-home-charging-guide-rialto-ca", title: "Level 1 vs. Level 2 charging at home", body: null, intro: "The source guide compares standard-outlet charging with a dedicated Level 2 setup. The right choice depends on your vehicle, daily mileage and home installation.", sections: ["Consider how much charge you need between trips, not just maximum charging speed.", "Ask a qualified electrician to assess the installation, circuit and equipment requirements. Actual costs and charging performance vary.", "Check your utility plan, vehicle specifications and expected length of stay in your home. Source cost and charging-rate estimates are not quotes or guarantees."] },
] as const;

export const SITE_PAGES: Record<string, { title: string; intro: string; kind?: string }> = {
  "/contact-us": { title: "Let's talk cars", intro: "Questions about a vehicle, a test drive, or your next step? Start here.", kind: "contact" },
  "/find-my-car": { title: "Your next car. Your criteria.", intro: "Tell us what you are looking for—even if it is not in the demo inventory.", kind: "find-my-car" },
  "/sell-my-car": { title: "Ready for your next chapter?", intro: "Explore the trade-appraisal experience. No lookup, valuation or offer is generated in this demo.", kind: "trade-appraisal" },
  "/finance-your-car": { title: "A clearer path to financing", intro: "Explore the next steps in English or Spanish. Financing providers are not connected in this private demo.", kind: "finance" },
  "/finance-your-car/pre-approved": { title: "Financing application preview", intro: "RouteOne integration placeholder. No application is submitted and no credit check is performed.", kind: "provider" },
  "/solicitar-financiacion": { title: "Solicitar financiación", intro: "Vista de demostración de RouteOne. No se envía ninguna solicitud ni se realiza una consulta de crédito.", kind: "provider-es" },
  "/capital-one-pre-qualify-then-shop": { title: "Capital One prequalification preview", intro: "A separate provider experience. This demo is not connected to Capital One and cannot determine eligibility.", kind: "provider" },
  "/bad-credit-financing-in-bloomington-ca": { title: "Questions about financing?", intro: "Discuss your options with the dealership and a financing provider. Approval, rates and terms are not guaranteed.", kind: "finance" },
  "/about-us": { title: "For wherever life takes you", intro: "Carfam is a used-car dealership in Rialto serving the Inland Empire, with a mix of cars, trucks and SUVs for different lifestyles.", kind: "about" },
  "/meet-our-team": { title: "Meet the team", intro: "A personal connection starts with a conversation.", kind: "staff" },
  "/customer-gallery-at-carfam": { title: "Part of the Carfam", intro: "Customer photography from the original site. This gallery is not a verified review feed.", kind: "customers" },
  "/used-car-dealer-serving-the-community-in-rialto": { title: "Rooted in Rialto", intro: "The original site describes community outreach and historic 2017–2018 recognition. Current partnerships and awards require dealer confirmation.", kind: "community" },
  "/careers": { title: "Start a conversation about careers", intro: "The captured careers page directs inquiries to the contact form. No current vacancy or hiring commitment is implied.", kind: "careers" },
  "/resources": { title: "A little knowledge. A better decision.", intro: "Browse buying guides, body styles and EV ownership topics adapted from the captured site.", kind: "resources" },
  "/news": { title: "Automotive news", intro: "The original site references Edmunds for automotive news. External content opens separately.", kind: "news" },
  "/ada-policy-statement": { title: "Accessibility", intro: "A dealership-approved accessibility statement is pending. The original route returned privacy-policy content, so this demo does not invent an ADA policy.", kind: "accessibility" },
  "/privacy-policy": { title: "Demo privacy notice", intro: "This private demo stores non-sensitive form requests in its local demo inbox. It does not send email, SMS, credit applications or marketing events.", kind: "privacy" },
  "/privacy-rights": { title: "Privacy rights", intro: "The dealership's production privacy terms and request process require approval before launch. Do not enter sensitive personal or financial information into this demo.", kind: "privacy" },
  "/account/login": { title: "Saved on your device", intro: "Customer accounts are not part of this demo. Saved vehicles and comparisons stay on this device.", kind: "account" },
  "/account/forgot-password": { title: "Customer accounts", intro: "There is no customer account or password to reset in this demo. Your saved vehicles stay on this device.", kind: "account" },
  "/visual-sitemap": { title: "Explore Carfam", intro: "All the public pages in this demo, in one place.", kind: "sitemap" },
};

export const PUBLIC_ROUTES = ["/", "/pre-owned-cars", "/saved", "/compare", ...Object.keys(SITE_PAGES), ...GUIDES.map((g) => g.path)];
