import Image from "next/image";
import Link from "next/link";
import { FinanceCalculator } from "@/components/forms/finance-calculator";
import { ApplicationPreview } from "./application-preview";
import { FINANCE_LINKS, type FinanceVehicle } from "@/lib/finance";
import { DEALER, formatPhone, telHref } from "@/lib/site";

const FAQ = [
  ["How do I estimate a monthly payment?", "Choose an inventory vehicle below, then try a down payment, trade-in value, APR and loan term. The result is an illustration, not a financing quote. Your actual rate and terms must come from a lender."],
  ["Can I apply in Spanish?", "Yes, the Spanish page previews the dealer financing process in Spanish. The live Spanish provider application will need to be connected before applications can be submitted."],
  ["Does this demo check my credit?", "No. There are no lender submissions, credit checks, prequalification results or approvals in this demo."],
  ["What is included in the displayed price?", "The listed sale price includes the dealer document and smog fees. Review the calculator disclosure for exclusions such as tax and registration. A lender's final amount and terms may differ."],
];
export function FinancePages({ route, vehicles }: { route: string; vehicles: FinanceVehicle[] }) {
  const spanish = route === "/solicitar-financiacion";
  const application = spanish || route === "/finance-your-car/pre-approved";
  const capital = route === "/capital-one-pre-qualify-then-shop";
  const badCredit = route === "/bad-credit-financing-in-bloomington-ca";
  const title = spanish ? "Tu próximo auto empieza aquí." : application ? "Your next chapter starts here." : capital ? "Pre-qualify. Then find your car." : badCredit ? "Your credit story isn't the whole story." : "Let's find your way forward.";
  const intro = spanish ? "Explora el proceso de financiación en español. Conoce los pasos y encuentra un vehículo que se adapte a ti." : application ? "See how the dealer financing process works, one step at a time. Explore the walkthrough before you talk with our team." : capital ? "Explore the Capital One financing path, then shop the vehicles that fit your needs. This is a separate experience from dealer financing." : badCredit ? "Working through credit challenges? Start with a conversation about your needs, your budget and the vehicle you’re looking for." : "A great car starts with a plan that fits your life. Explore financing paths, compare vehicles and get a clearer picture of your monthly budget.";
  return <div lang={spanish ? "es" : "en"}>
    <section className="on-dark relative isolate overflow-hidden bg-graphite text-paper">
      <Image unoptimized src="/brand/finance-background.jpg" alt="" fill sizes="100vw" className="-z-20 object-cover object-right" />
      <div className="absolute inset-0 -z-10 bg-gradient-to-r from-graphite via-graphite/95 to-graphite/55" />
      <div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 sm:py-24">
        <Link href="/finance-your-car" className="text-sm text-fog hover:text-paper">Carfam / {spanish ? "Financiación" : "Financing"}</Link>
        <p className="mt-10 text-xs font-bold uppercase tracking-[0.2em] text-cyan">{spanish ? "A tu ritmo. A tu manera." : "Your car. Your next step."}</p>
        <h1 className="font-display mt-4 max-w-3xl text-4xl leading-tight sm:text-6xl">{title}</h1>
        <p className="mt-6 max-w-xl text-lg leading-relaxed text-fog">{intro}</p>
        <div className="mt-8 flex flex-wrap gap-3">
          <Link className="button" href={application ? "#application-preview" : capital ? "#capital-one-preview" : "/finance-your-car/pre-approved"}>{spanish ? "Ver el recorrido" : application ? "Explore the application steps" : capital ? "Explore Capital One" : "Explore financing"} →</Link>
          <Link className="button-secondary" href={spanish ? "/finance-your-car/pre-approved" : application ? "/solicitar-financiacion" : "/pre-owned-cars"}>{spanish ? "In English" : application ? "En español" : "Shop vehicles"}</Link>
        </div>
        <p className="mt-7 max-w-xl text-xs leading-relaxed text-fog">{spanish ? "Solo demostración. Sin solicitudes, consultas de crédito ni decisiones de financiación." : "Demo experience · No lender submissions, credit checks or financing decisions."}</p>
      </div>
    </section>
    <nav aria-label={spanish ? "Opciones de financiación" : "Financing options"} className="border-b border-line bg-paper">
      <div className="mx-auto flex max-w-7xl flex-wrap gap-x-6 gap-y-1 px-4 py-4 sm:px-6">{FINANCE_LINKS.map((item) => <Link key={item.href} href={item.href} aria-current={route === item.href ? "page" : undefined} className="flex min-h-11 items-center border-b-2 border-transparent text-sm font-semibold text-slate hover:text-ink aria-[current=page]:border-cyan aria-[current=page]:text-ink">{spanish && item.href === "/finance-your-car" ? "Departamento de financiación" : item.label}</Link>)}</div>
    </nav>
    <div className="mx-auto max-w-7xl space-y-14 px-4 py-12 sm:space-y-20 sm:px-6 sm:py-20">
      {application ? <section id="application-preview" className="scroll-mt-24 grid items-start gap-8 lg:grid-cols-[0.8fr_1.2fr]">
        <div className="space-y-5"><p className="text-xs font-bold uppercase tracking-widest text-cyan-ink">{spanish ? "Financiación del concesionario" : "Dealer financing"}</p><h2 className="font-display text-3xl">{spanish ? "Prepárate para el siguiente paso." : "A little clarity before you apply."}</h2><p className="leading-relaxed text-slate">{spanish ? "El sitio original utiliza RouteOne para las solicitudes en español. Aquí puedes explorar las etapas del proceso sin compartir información privada." : "Carfam's original dealer application uses RouteOne. Here you can explore its application stages without sharing private information."}</p><p className="leading-relaxed text-slate">{spanish ? "Este recorrido explica las etapas; no reproduce los campos ni los requisitos del proveedor. El proveedor debe confirmar sus requisitos y condiciones." : "This walkthrough explains the stages; it does not reproduce the provider's fields or requirements. The provider must confirm its own requirements and terms."}</p><ContactPanel spanish={spanish} /></div>
        <ApplicationPreview spanish={spanish} vehicles={vehicles} />
      </section> : capital ? <CapitalOne /> : badCredit ? <BadCredit /> : <>
        <section className="grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-widest text-cyan-ink">Finance department</p><h2 className="font-display mt-3 text-3xl sm:text-4xl">A plan for the road ahead.</h2><p className="mt-5 leading-relaxed text-slate">From your first commuter to the family SUV, start with what matters to you. Explore a comfortable budget, find a vehicle you like and talk through the next steps with Carfam.</p><Link href="#payment-calculator" className="mt-6 inline-flex font-bold text-cyan-ink underline">Estimate a payment →</Link></div><Steps items={[["Find your fit", "Browse the inventory and compare the complete listed sale prices."], ["Explore your budget", "Try different down payments and terms in the illustrative calculator."], ["Talk through the next steps", "Ask the dealership about the provider process. A lender determines eligibility, rates and terms."]]} /></section>
        <section><h2 className="font-display text-3xl">Choose your financing path.</h2><div className="mt-7 grid gap-4 md:grid-cols-2">{FINANCE_LINKS.slice(1).map((item, index) => <Link href={item.href} className="page-card group" key={item.href}><p className="text-xs font-bold uppercase tracking-widest text-cyan-ink">0{index + 1} / {index === 2 ? "Separate provider" : index === 3 ? "Let's talk" : "Dealer financing"}</p><h3 className="font-display mt-4 text-2xl">{item.label}</h3><p className="mt-3 text-slate">{item.description}</p><span className="mt-5 inline-flex font-semibold text-cyan-ink group-hover:underline">Explore →</span></Link>)}</div></section>
      </>}
      {!application && !capital && <section id="payment-calculator" className="scroll-mt-24 rounded-2xl border border-line bg-paper p-5 sm:p-8"><p className="text-xs font-bold uppercase tracking-widest text-cyan-ink">Plan your budget</p><p className="mt-3 max-w-2xl leading-relaxed text-slate">Start with a vehicle from our demo inventory. Change the numbers to explore a payment that works for you; your estimate stays in this browser and is not sent to a lender.</p><FinanceCalculator vehicles={vehicles} /></section>}
      {!spanish && <section><h2 className="font-display text-3xl">A few helpful answers.</h2><div className="mt-7 divide-y divide-line border-y border-line">{FAQ.map(([question, answer]) => <details key={question} className="group py-5"><summary className="cursor-pointer text-lg font-semibold">{question}</summary><p className="mt-4 max-w-3xl leading-relaxed text-slate">{answer}</p></details>)}</div></section>}
      <section className="rounded-2xl bg-graphite p-7 text-paper sm:p-10"><div className="flex flex-col items-start justify-between gap-6 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-widest text-cyan">{spanish ? "Estamos aquí para ayudarte" : "A real conversation starts here"}</p><h2 className="font-display mt-3 text-3xl">{spanish ? "¿Tienes preguntas? Hablemos." : "Questions? Let's talk."}</h2><p className="mt-3 max-w-xl text-fog">{spanish ? "Habla con nuestro equipo sobre los próximos pasos. No envíes datos financieros privados mediante el formulario de contacto." : "Talk with our team about the next steps. Keep private financial details out of the contact form."}</p></div><a href={telHref(DEALER.salesPhone)} className="button">{spanish ? "Llamar" : "Call Carfam"} {formatPhone(DEALER.salesPhone)}</a></div></section>
    </div>
  </div>;
}

function Steps({ items }: { items: string[][] }) {
  return <ol className="space-y-4">{items.map(([title, body], index) => <li className="flex gap-5 rounded-xl border border-line p-5" key={title}><span className="font-display text-3xl text-cyan-ink">0{index + 1}</span><div><h3 className="font-display text-xl">{title}</h3><p className="mt-2 leading-relaxed text-slate">{body}</p></div></li>)}</ol>;
}
function ContactPanel({ spanish = false }: { spanish?: boolean }) {
  return <div className="rounded-xl bg-mist p-5"><h3 className="font-display text-xl">{spanish ? "¿Prefieres hablar con alguien?" : "Prefer to talk it through?"}</h3><a href={telHref(DEALER.salesPhone)} className="mt-3 inline-flex min-h-11 items-center font-bold text-cyan-ink underline">{formatPhone(DEALER.salesPhone)}</a><p className="mt-2 text-sm text-slate">{DEALER.street} · {DEALER.city}, {DEALER.region}</p></div>;
}
function CapitalOne() {
  return <section id="capital-one-preview" className="scroll-mt-24 grid gap-8 lg:grid-cols-2"><div className="space-y-5"><Image unoptimized src="/brand/capital-one-logo.svg" width={200} height={75} alt="Capital One" className="h-16 w-auto" /><p className="text-xs font-bold uppercase tracking-widest text-cyan-ink">A separate financing path</p><h2 className="font-display text-3xl">Explore first. Shop with a plan.</h2><p className="leading-relaxed text-slate">Carfam’s original site offers a separate Capital One prequalification experience. It has its own application, disclosures and consent process, separate from the RouteOne dealer application.</p><p className="leading-relaxed text-slate">Prequalification and final loan approval are separate steps. The provider must confirm current eligibility, participating vehicles and terms.</p><div className="rounded-xl border border-line bg-mist p-6"><h3 className="font-display text-xl">Capital One demo preview</h3><p className="mt-3 text-sm leading-relaxed text-slate">The lender experience is not connected. This page does not collect application information, check credit or show a prequalification result.</p><Link href="/pre-owned-cars" className="button mt-5">Browse demo inventory →</Link></div></div><Steps items={[["Explore prequalification", "In a live integration, Capital One would collect its required information and present its own disclosures."], ["Shop for your vehicle", "Compare vehicles and review the provider’s current eligibility criteria. This demo cannot label a vehicle as lender eligible."], ["Review the final terms", "Confirm the price, financing terms and all required documentation with the dealership and lender before proceeding."]]} /></section>;
}
function BadCredit() {
  return <section className="grid gap-8 lg:grid-cols-2"><div className="space-y-5"><p className="text-xs font-bold uppercase tracking-widest text-cyan-ink">Bad credit financing questions</p><h2 className="font-display text-3xl">Start where you are.</h2><p className="leading-relaxed text-slate">If you’ve had credit challenges, you can still start a conversation about buying a car. Tell our team what you’re looking for and ask about the financing process. Approval, rates and terms depend on the lender; nothing is guaranteed.</p><p className="leading-relaxed text-slate">Shopping from Bloomington or nearby? Carfam is located in Rialto. Explore vehicles and discuss your next steps with the dealership before sharing private financial information with a provider.</p><ContactPanel /></div><div className="rounded-2xl bg-mist p-6 sm:p-8"><h3 className="font-display text-2xl">Make the conversation count.</h3><ul className="mt-5 list-disc space-y-4 pl-5 text-slate"><li>Which vehicles fit the budget you have in mind?</li><li>How could a down payment or trade-in change the amount financed?</li><li>What documentation would the actual lender require?</li><li>What are the APR, term, total payments and final fees?</li><li>Which provider handles the application and credit authorization?</li></ul><Link href="/finance-your-car/pre-approved" className="mt-7 inline-flex font-bold text-cyan-ink underline">Preview the dealer application steps →</Link></div></section>;
}
