/* eslint-disable @next/next/no-img-element -- The runtime optimizer is off (next.config.ts); sizes are
   pre-generated by `npm run photos:variants` and chosen here with <picture>/srcset. */
import type { SyntheticEvent } from "react";
import {
  hasPhotoVariants,
  ORIGINAL_PHOTO_WIDTH,
  photoSrcSet,
  photoVariantPath,
} from "@/lib/inventory/photo-variants";

/**
 * - card:    phones (< 640px wide) always get the 480px WebP; larger screens pick 480/960 by density.
 * - gallery: main detail photo; full srcset (480/960 WebP, 1200 JPEG original).
 * - thumb:   480px WebP only.
 * - full:    lightbox; the 1200×900 original.
 */
export type PhotoUse = "card" | "gallery" | "thumb" | "full";

const CARD_SIZES = "(min-width: 1280px) 360px, (min-width: 640px) 45vw, 100vw";
const GALLERY_SIZES = "(min-width: 1280px) 820px, (min-width: 1024px) 62vw, 100vw";

export function VehiclePhoto({
  src,
  alt,
  use,
  priority = false,
  className = "",
  onError,
  draggable,
}: {
  src: string;
  alt: string;
  use: PhotoUse;
  priority?: boolean;
  className?: string;
  onError?: (e: SyntheticEvent<HTMLImageElement>) => void;
  draggable?: boolean;
}) {
  const common = {
    width: ORIGINAL_PHOTO_WIDTH,
    height: 900,
    loading: priority ? ("eager" as const) : ("lazy" as const),
    fetchPriority: priority ? ("high" as const) : undefined,
    decoding: "async" as const,
    onError,
    draggable,
    className,
  };

  if (!hasPhotoVariants(src) || use === "full") return <img src={src} alt={alt} {...common} />;
  if (use === "thumb") return <img src={photoVariantPath(src, 480)} alt={alt} {...common} />;
  if (use === "gallery") {
    return <img src={src} srcSet={photoSrcSet(src)} sizes={GALLERY_SIZES} alt={alt} {...common} />;
  }

  const small = photoVariantPath(src, 480);
  return (
    <picture>
      <source media="(max-width: 639px)" srcSet={small} type="image/webp" />
      <img
        src={small}
        srcSet={`${small} 480w, ${photoVariantPath(src, 960)} 960w`}
        sizes={CARD_SIZES}
        alt={alt}
        {...common}
      />
    </picture>
  );
}
